### ISSUE TITLE
Prevent nested creation and updates

### ISSUE THREAD

**Issue by A-Boudi** [jsonapi-suite/strong_resources#11]
I'm trying to prevent jsonapi from updating nested resources. I still need to provide the relationships when storing the data but I don't want to permit the creation/update of the nested resources. The user should only be able to reference already existing data for it's relationships.

I tried to copy the behavior of disassociate and destroy, but even if we don't provide the method in the json body the nested resources are still being updated. I didn't understand the use of :only and :except, I don't know if they can do what I'm trying to do.

Can you please help me find where I can enforce this behavior?

**Comment by richmolj** [comment]
@A-Boudi so you want to be able to pass the id, but no other properties? `only: [:id]` should work

**Comment by A-Boudi** [comment]
Thank you very much.
